### ISSUE TITLE
rtkernel for BBB

### ISSUE THREAD

**Issue by ZiweiHuang94** [cfsd/opendlv.os#4]

**Comment by chrberger** [comment]
Hi @ZiweiHuang94, can you please provide more detailed issue descriptions? Otherwise, it is difficult to provide support. Thanks.

**Comment by ZiweiHuang94** [comment]
Sorry for bothering you with the issue. I did not intend to ask for help from you. I put them because I would like to remind myself to solve them. I will remove the issues to avoid misunderstandings.
